### ISSUE TITLE
Error: Cannot find module 'gulp-jsinspect'

### ISSUE THREAD

**Issue by luanmuniz** [alexeyraspopov/gulp-jsinspect#2]
You Need to deploy this into npm
The module is empty there

**Comment by Sk1Zy** [comment]
Agreed, doesn't work.

**Comment by alexzaporozhets** [comment]
```
npm i gulp-jsinspect
ls node_modules/gulp-jsinspect
package.json	readme.md
```

**Comment by luanmuniz** [comment]
Yes. There is no js file

**Comment by alexzaporozhets** [comment]
this package looks totally broken

**Comment by ccnokes** [comment]
Still broken.

**Comment by binarykitchen** [comment]
yeah, broken

**Comment by Semigradsky** [comment]
@luanmuniz  @Sk1Zy  @alexzaporozhets  @ccnokes  @binarykitchen 
Hello! I am create worked version if you interesting: [jsinspect-gulp](https://github.com/Semigradsky/jsinspect-gulp)

Install:
`npm install --save-dev jsinspect-gulp`

**Comment by callumacrae** [comment]
@alexeyraspopov Would you be willing to add @Semigradsky as an owner to the gulp-jsinspect package on npm? Your package doesn't do anything and his works—unless you're planning on finishing this project soon, it would be great if you could hand over control to him :smiley:

**Comment by alexeyraspopov** [comment]
@Semigradsky you're added. Feel free to update this package. I want to say sorry for all of you guys, it was strange period of my life and I wasn't able to find a time to finish this plugin.

**Comment by callumacrae** [comment]
@alexeyraspopov Thanks! No worries—everyone has difficult times at some point.

**Comment by Semigradsky** [comment]
@alexeyraspopov 
Thanks! But I can not some things, publish to npm for example. Maybe you must add me as *owner*

**Comment by alexeyraspopov** [comment]
@Semigradsky [done](https://www.npmjs.com/package/gulp-jsinspect/access)

**Comment by Semigradsky** [comment]
:+1: 
Yeah, I published some packages with leading zeroes :disappointed:

**Comment by Semigradsky** [comment]
New version in npm

**Comment by alexeyraspopov** [comment]
@Semigradsky can you also push tags to origin? Thanks
